### ISSUE TITLE
Chrome 개발자 모드 console 오류

### ISSUE THREAD

**Issue by ebcode2021** [42-Jolly-pingpong/front-end#12]
footer 부분에 chat, friend 버튼 클릭시

```
react-dom.development.js:86 Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at div
    at ChatList (http://localhost:3000/static/js/bundle.js:1906:84)
    at div
    at Chat
    at div
    at Sidebar (http://localhost:3000/static/js/bundle.js:2715:71)
    at div
    at Section (http://localhost:3000/static/js/bundle.js:41:78)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:43364:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:43913:26)
    at div
    at div
    at Layout
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:43364:5)
    at Routes (http://localhost:3000/static/js/bundle.js:43996:5)
    at Router (http://localhost:3000/static/js/bundle.js:43934:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:42037:5)
    at RecoilRoot_INTERNAL (http://localhost:3000/static/js/bundle.js:51572:3)
    at RecoilRoot (http://localhost:3000/static/js/bundle.js:51716:5)
    at div
    at App
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
checkControlledValueProps @ react-dom.development.js:1596
initWrapperState @ react-dom.development.js:1775
setInitialProperties @ react-dom.development.js:9888
finalizeInitialChildren @ react-dom.development.js:10950
completeWork @ react-dom.development.js:22193
completeUnitOfWork @ react-dom.development.js:26596
performUnitOfWork @ react-dom.development.js:26568
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
```

에러가 뜹니다. 확인 부탁드려요!

**Comment by SOONG-E** [comment]
어떤 브런치고 어떤 상태인 거죠..? 이렇게 봐서는 아무것도 모르겠네여.. 일단 최신상태 dev브런치는 같은 에러가 안생깁니다

**Comment by ebcode2021** [comment]
최신상태 dev branch에서, chat 이나 friend 버튼을 클릭할 때 chrome 개발자모드 console창에서 발생하는 warning 입니다.
클릭할때마다 생겨요!
다음부턴 자세히 남기겠습니다~~

**Comment by SOONG-E** [comment]
수정했습니다! pr확인해주세요
